### ISSUE TITLE
SUPIR model output image resolution became very low now

### ISSUE THREAD

**Issue by fgtm2023** [fal-ai/upscaler-battleground-demo-app#13]
Hi, previously SUPIR and CCSR models output image resolutions were equaled and cap to 1024 pixel, now SUPIR output res became very low and in a lot of situations under 1024 pixel cap by huge margin, now SUPPIR output is 1024 Pixel is when input image is 1024 pixel or 512 pixel !!!!!! , thanks a lot for your amazing work.

**Comment by aykutkardas** [comment]
The SUPIR model does not have an upscale limit. However, in this demo project, images are resized to 512 pixels and some noise effects are added. 

You can use our platform to test the models in more detail.
 https://fal.ai/models/supir
